dependencies:
  # - <organization/repo>@<version> This is the format to be used.
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
  - OpenZeppelin/openzeppelin-contracts@4.7.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.1"

networks:
  mainnet-fork-dev2:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False